export const HEALTHLOQ_GET_PRODUCT_LIST = "HEALTHLOQ_GET_PRODUCT_LIST";
export const HEALTHLOQ_GET_BATCH_INFO = "HEALTHLOQ_GET_BATCH_INFO";
export const READ_COA_USING_DOCUMENT_AI = "READ_COA_USING_DOCUMENT_AI";
export const BROWSE_PRODUCTS_FROM_NIH_DATABASE =
  "BROWSE_PRODUCTS_FROM_NIH_DATABASE";
export const GET_NIH_LABEL_INFO = "GET_NIH_LABEL_INFO";
export const UPDATE_FORM_FIELDS = "UPDATE_FORM_FIELDS";
